CREATE OR ALTER VIEW deuda_cliente_vendedor_v AS
SELECT CS.IDVENDEDOR,
	   RESULT.IDCLIENTE, RESULT.IDENC_MOV, RESULT.TOTAL,
	   RPAD(CC.TIPOCOMPROB, 4, ' ') || RPAD(CC.LETRA, 2, ' ') || LPAD(CC.TERMINAL, 4, '0') || '-' || LPAD(CC.NUMERO, 8, '0') COMPROBANTE,
	   CC.FECHA, CC.FECHA + PV.DIASCOB1 VENCE,
       DATEDIFF(DAY, CC.FECHA + PV.DIASCOB1, CURRENT_DATE) DIAS
FROM 
(
  SELECT IDCLIENTE, REF_IDENC_MOV AS IDENC_MOV, SUM(IMPORTE) TOTAL
  FROM CUENTACTE
  GROUP BY IDCLIENTE, REF_IDENC_MOV
  HAVING SUM(IMPORTE) > 0
) RESULT
INNER JOIN CUENTACTE CC ON CC.IDENC_MOV = RESULT.IDENC_MOV
INNER JOIN CLIENTESSUCURSAL CS ON CS.IDCLIENTE = CC.IDCLIENTE
INNER JOIN PTOVTA PV ON PV.PTOVTA = CC.TERMINAL
WHERE DATEDIFF(DAY, CC.FECHA + PV.DIASCOB1, CURRENT_DATE) > 0;


/*
-- calcula total por cada 15 días (0, 15, 20, 45 días)
-- para realizar gráfica
SELECT 15*(dias/15) q, ROUND(sum(total),2) suma
FROM DEUDA_CLIENTE_VENDEDOR_V
where ((vence > '2019-01-01') and (vence < '2019-05-21'))
GROUP BY q
*/