# Generated by Django 2.2.1 on 2019-05-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('001', 'Llamada'), ('002', 'Visita'), ('003', 'Intimación'), ('004', 'Actuación Judicial'), ('005', 'Cobrado')], default='001', max_length=5)),
                ('observacion', models.TextField()),
                ('idenc_mov', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Accion',
                'verbose_name_plural': 'Acciones',
            },
        ),
    ]
